### ISSUE TITLE
Câu hỏi cho buổi học ngày 12/05 (MSSV: 1712718 - Huỳnh Thanh Sang - nhóm 5)

### ISSUE THREAD

**Issue by hts7117** [kimdinhloc/Applied_Parallel_Programming_HK2_2021_2022#1]
Mình có một câu hỏi là ở mô hình hóa song song dự kiến của nhóm bạn xong sau thực hiện xong "GRABCUT" và "Compute new cluster" thì dữ liệu sẽ được đưa vào host để tính toán cho giai đoạn "GRABMASK" sau đó lại đưa vào device để tính tiếp.
Không biết nếu mình đưa dữ liệu sau "GRABCUT" vào device luôn rồi gộp chung với "compute new cluster" để tính GRABMASK k biết có được không và một trong 2 cách thì cách nào sẽ đem lại tốc độ cao hơn.

**Comment by kimdinhloc** [comment]
Chúng ta hoàn toàn có thể song song hóa bước đó. Việc đó sẽ tiết kiệm 1 lần copy mảng từ Device sang Host. Nếu việc song song đối với image có ảnh lớn thì tốc độ sẽ cải thiện càng nhiều so với chạy trên Host.
